#!/bin/sh

#xrdb $HOME/.Xresources
#xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
#export XKL_XMODMAP_DISABLE=1
#autocutsel -fork
#/etc/X11/Xsession
#lxterminal &
#/usr/bin/lxsession -s LXDE &

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

#autocutsel -fork
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#xsetroot -solid grey
#lxterminal &
vncconfig -nowin &
/usr/bin/lxsession -s LXDE &
/etc/X11/Xsession
